SHELL=/bin/bash

NODE=node
PANDOC=pandoc

# markpress executable generated by @make deps
MARKPRESS_BIN=./node_modules/markpress/bin/markpress.js
# The impress.js generated layout [horizontal (default)|vertical|3d-push|3d-pull|grid|random-7d|random]
MARKPRESS_LAYOUT=3d-push

PANDOC_CSS=css/impress.css
PANDOC_INPUT=markdown
PANDOC_OUTPUT=html5

INPUT=presentation.md
OUTPUT=index.html
BOOK=book.html

build:
	# Build impress.js HTML from Markdown source
	${NODE} --harmony ${MARKPRESS_BIN} --input ${INPUT} --output ${OUTPUT} --no-embed --layout ${MARKPRESS_LAYOUT}
	# Build book version from Markdown souce
	${PANDOC} --standalone --from ${PANDOC_INPUT} --to ${PANDOC_OUTPUT} --css ${PANDOC_CSS} --output ${BOOK} ${INPUT}

deps:
	sudo aptitude install npm
	npm install markpress

